# Generated by Django 4.2.7 on 2023-11-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadogeometria',
            name='area_km2',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='municipios_vizinhos',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='visivel',
        ),
    ]
