# Generated by Django 4.2.7 on 2023-11-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0002_remove_estadogeometria_area_km2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipiogeometria',
            name='retificado',
        ),
    ]
