# Generated by Django 4.2.7 on 2023-11-05 12:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('nome_acao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Ação')),
                ('nome_comunidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Comunidade')),
                ('localidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localidade')),
                ('organizacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organização')),
                ('categoria', models.CharField(blank=True, max_length=255, null=True, verbose_name='Categoria')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('municipio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Município')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Geometria')),
            ],
            options={
                'verbose_name': 'ação',
                'verbose_name_plural': 'Ações',
            },
        ),
    ]
