# Generated by Django 4.2.7 on 2023-11-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='premiado',
            field=models.BooleanField(default=False, verbose_name='Premiado?'),
        ),
    ]
